
export { default as CssIcon } from "./CSSIcon"
export { default as HtmlIcon } from "./HtmlIcon"
export { default as JsIcon } from "./jsIcon"
export { default as JsonIcon } from "./JSONicon"
export { default as JsxIcon } from "./jsxIcon"
export { default as PdfIcon } from "./pdfIcon"
export { default as PyIcon } from "./PyIcon"
export { default as TsxIcon } from "./tsxIcons"
export { default as TxtIcon } from "./TXTicon"
export { default as JavaIcon } from "./JAVAicon"
export { default as CppIcon } from "./CPPIcon"
export { default as CIcon } from "./Cicon"
export { default as MDIcon } from "./mdIcon"
export { default as PHPIcon } from "./PHPicon"
export { default as RSIcon } from "./RSicon"
export { default as SwiftIcon } from "./SWIFTicon"
export { default as XML } from "./XMLicon"
export { default as YAMl } from "./YAMLicon"
export { default as RubyIcon } from "./Rubyicon"
export { default as ShellIcon } from "./Shicon"
export { default as GoIcon } from "./Goicon"
export { default as CSIcon } from "./CSicon"
export { default as CSVIcon } from "./CSVicon"
export { default as LogIcon } from "./LogIcon"

