export const TIPS = [
    "I can search and extract information from any webpage",
    "I work best when you give me clear, specific instructions",
    "I can browse the web and gather information from multiple sources",
    "You can copy and paste files directly into the chat input",
    "You can drag and drop files into the chat input",
    "Ask me to organize your tabs for you",
    "I can analyze YouTube videos for you",
    "You can send messages to Cognito by typing 'ai' in the address bar",
    "Set keyboard shortcuts at chrome://extensions/shortcuts for quick access",
    "Customize which AI tools are enabled in Settings → Enabled Tools",
    "Toggle suggested actions on/off in Settings ",
    "Choose between Gemini TTS or Web Native TTS in Settings",
    "Delete all chat history anytime from Settings ",
    "Control Ask AI button visibility per domain in Settings",
    "Enable Supermemory in Settings to let me remember things about you across conversations",
    "Select text on any page to see Summarize and Rewrite options",
    "Type /write in any text field to generate AI content instantly",
    "Type /ask in any text field to ask questions about the page",
    "Configure Tavily API key in Settings for enhanced web search",
    "Adjust max tool calls in Settings to control AI tool usage (max steps)",
    "Set up reminders that trigger at specific times or contexts",
    "Choose basic or advanced search depth in Web Search settings",
    "Enable Memory Search in /ask to query your Supermemory",
    "Customize summary type and length in Text Summarizer settings",
    "Toggle preset buttons in Text Rewriter for quick rewrites",
    "Set minimum text length for Summarizer and Rewriter tools",
    "Include page context, selection, or visible content in /ask",
    "Add YouTube videos by clicking on the attachment icon"
];

